/**
 * Ruler file migration utilities
 * Copies .ruler/*.md files to .aligntrue/rules/ preserving multi-file structure
 */

import { readFileSync, writeFileSync } from "fs";
import { join, basename } from "path";
import { glob } from "glob";
import { ensureDirectoryExists } from "@aligntrue/file-utils";

/**
 * Check if AGENTS.md contains AlignTrue's read-only marker
 * Returns true if file has our marker, false otherwise
 */
export function isAlignTrueGenerated(agentsMdPath: string): boolean {
  try {
    const content = readFileSync(agentsMdPath, "utf-8");
    return (
      content.includes("READ-ONLY") &&
      content.includes("auto-generated by AlignTrue")
    );
  } catch {
    return false;
  }
}

/**
 * Add or update frontmatter for a ruler markdown file
 * Extracts title from filename if not present in content
 *
 * @param content - File content
 * @param filename - Original filename (e.g., "testing.md")
 * @returns Content with frontmatter added/updated
 */
export function addFrontmatterToRulerFile(
  content: string,
  filename: string,
): string {
  // Extract title from filename (remove .md, replace hyphens/underscores with spaces, capitalize)
  const title = filename
    .replace(/\.md$/, "")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  // Check if content already has frontmatter
  const hasFrontmatter = content.trim().startsWith("---");

  if (hasFrontmatter) {
    // Extract existing frontmatter and content
    const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (match) {
      const frontmatterContent = match[1];
      const bodyContent = match[2];
      // Ensure title exists in frontmatter
      if (!frontmatterContent?.includes("title:")) {
        const updatedFrontmatter = `title: ${title}\n${frontmatterContent}`;
        return `---\n${updatedFrontmatter}\n---\n${bodyContent}`;
      }
      return content; // Already has title
    }
  }

  // No frontmatter, add one
  return `---\ntitle: ${title}\n---\n\n${content}`;
}

/**
 * Copy ruler markdown files to .aligntrue/rules/
 * Preserves multi-file structure and adds frontmatter
 *
 * @param rulerDir - Path to .ruler/ directory
 * @param targetDir - Path to .aligntrue/rules directory
 * @returns Array of copied filenames
 */
export async function copyRulerFilesToAlignTrue(
  rulerDir: string,
  targetDir: string,
): Promise<string[]> {
  // Ensure target directory exists
  ensureDirectoryExists(targetDir);

  // Find all .md files in .ruler/
  let mdFiles = glob.sync("**/*.md", {
    cwd: rulerDir,
    ignore: ["node_modules/**"],
  });

  // Normalize to forward slashes for cross-platform consistency
  mdFiles = mdFiles.map((p) => p.replace(/\\/g, "/"));

  // Sort alphabetically
  mdFiles.sort();

  const copiedFiles: string[] = [];

  for (const relPath of mdFiles) {
    const sourcePath = join(rulerDir, relPath);
    const targetPath = join(targetDir, relPath);

    // Ensure subdirectories in target exist
    const targetSubdir = join(
      targetDir,
      relPath.split("/").slice(0, -1).join("/"),
    );
    if (targetSubdir !== targetDir) {
      ensureDirectoryExists(targetSubdir);
    }

    // Read source file
    let content = readFileSync(sourcePath, "utf-8");

    // Add/update frontmatter
    const filename = basename(relPath);
    content = addFrontmatterToRulerFile(content, filename);

    // Write to target
    writeFileSync(targetPath, content, "utf-8");
    copiedFiles.push(relPath);
  }

  return copiedFiles;
}

/**
 * Determine if AGENTS.md should be included in rules migration
 * Returns true if:
 * - File exists
 * - Does NOT have AlignTrue's read-only marker
 */
export function shouldIncludeAgentsMd(projectCwd: string): boolean {
  const agentsMdPath = join(projectCwd, "AGENTS.md");

  try {
    const fs = require("fs");
    if (!fs.existsSync(agentsMdPath)) {
      return false;
    }
    // Include only if NOT generated by AlignTrue
    return !isAlignTrueGenerated(agentsMdPath);
  } catch {
    return false;
  }
}

/**
 * Copy AGENTS.md to .aligntrue/rules/agents.md
 *
 * @param projectCwd - Project root directory
 * @param targetDir - Path to .aligntrue/rules directory
 * @returns true if copied, false if not present or skipped
 */
export async function copyAgentsMdIfNeeded(
  projectCwd: string,
  targetDir: string,
): Promise<boolean> {
  const agentsMdPath = join(projectCwd, "AGENTS.md");

  try {
    const fs = require("fs");
    if (!fs.existsSync(agentsMdPath)) {
      return false;
    }

    // Skip if it's our generated file
    if (isAlignTrueGenerated(agentsMdPath)) {
      return false;
    }

    // Copy AGENTS.md to agents.md in rules directory
    const content = readFileSync(agentsMdPath, "utf-8");
    const targetPath = join(targetDir, "agents.md");

    // Add/update frontmatter
    const contentWithFrontmatter = addFrontmatterToRulerFile(
      content,
      "agents.md",
    );
    writeFileSync(targetPath, contentWithFrontmatter, "utf-8");

    return true;
  } catch {
    return false;
  }
}
