/**
 * Trae AI exporter
 * Exports AlignTrue rules to Trae AI .trae/rules/project_rules.md format
 */

import { join } from 'path'
import type { ExporterPlugin, ScopedExportRequest, ExportOptions, ExportResult, ResolvedScope } from '../types.js'
import type { AlignRule } from '@aligntrue/schema'
import { canonicalizeJson, computeHash } from '@aligntrue/schema'
import { AtomicFileWriter } from '@aligntrue/file-utils'

interface ExporterState {
  allRules: Array<{ rule: AlignRule; scopePath: string }>
}

export class TraeAiExporter implements ExporterPlugin {
  name = 'trae-ai'
  version = '1.0.0'
  
  private state: ExporterState = {
    allRules: [],
  }

  async export(request: ScopedExportRequest, options: ExportOptions): Promise<ExportResult> {
    const { scope, rules } = request
    const { outputDir, dryRun = false } = options

    if (!rules || rules.length === 0) {
      return {
        success: true,
        filesWritten: [],
        contentHash: '',
      }
    }

    const scopePath = this.formatScopePath(scope)
    rules.forEach(rule => {
      this.state.allRules.push({ rule, scopePath })
    })

    const outputPath = join(outputDir, '.trae', 'rules', 'project_rules.md')
    const content = this.generateProjectRulesContent()
    
    const allRulesIR = this.state.allRules.map(({ rule }) => rule)
    const irContent = JSON.stringify({ rules: allRulesIR })
    const contentHash = computeHash(canonicalizeJson(irContent))
    
    const fidelityNotes = this.computeFidelityNotes(allRulesIR)
    
    if (!dryRun) {
      const writer = new AtomicFileWriter()
      writer.write(outputPath, content)
    }

    const result: ExportResult = {
      success: true,
      filesWritten: dryRun ? [] : [outputPath],
      contentHash,
    }

    if (fidelityNotes.length > 0) {
      result.fidelityNotes = fidelityNotes
    }

    return result
  }

  resetState(): void {
    this.state = {
      allRules: [],
    }
  }

  private formatScopePath(scope: ResolvedScope): string {
    if (scope.isDefault || scope.path === '.' || scope.path === '') {
      return 'all files'
    }
    return scope.path
  }

  private generateProjectRulesContent(): string {
    const lines: string[] = []
    
    lines.push('# Project Rules')
    lines.push('')
    lines.push('**Version:** v1')
    lines.push('**Generated by:** AlignTrue')
    lines.push('')

    this.state.allRules.forEach(({ rule, scopePath }) => {
      lines.push(`## ${rule.id}`)
      lines.push('')
      lines.push(`**Severity:** ${rule.severity.toUpperCase()}`)
      if (scopePath) {
        lines.push(`**Scope:** ${scopePath}`)
      }
      lines.push('')
      if (rule.guidance) {
        lines.push(rule.guidance.trim())
        lines.push('')
      }
      lines.push('---')
      lines.push('')
    })

    const allRulesIR = this.state.allRules.map(({ rule }) => rule)
    const irContent = JSON.stringify({ rules: allRulesIR })
    const contentHash = computeHash(canonicalizeJson(irContent))
    const fidelityNotes = this.computeFidelityNotes(allRulesIR)

    lines.push('**Generated by AlignTrue**')
    lines.push(`Content Hash: ${contentHash}`)
    
    if (fidelityNotes.length > 0) {
      lines.push('')
      lines.push('**Fidelity Notes:**')
      fidelityNotes.forEach(note => {
        lines.push(`- ${note}`)
      })
    }

    return lines.join('\n')
  }

  private computeFidelityNotes(rules: AlignRule[]): string[] {
    const notes: string[] = []
    const unmappedFields = new Set<string>()

    rules.forEach(rule => {
      if (rule.check) {
        unmappedFields.add('check')
      }
      if (rule.autofix) {
        unmappedFields.add('autofix')
      }
    })

    if (unmappedFields.has('check')) {
      notes.push('Machine-checkable rules (check) not represented in .trae/rules/project_rules.md format')
    }
    if (unmappedFields.has('autofix')) {
      notes.push('Autofix hints not represented in .trae/rules/project_rules.md format')
    }

    return notes
  }
}

export default TraeAiExporter

