id: golden-repo-rules
version: 1.0.0
spec_version: "1"
sections:
  - heading: Testing requirements
    level: 2
    content: >
      Every new feature must include unit tests. Test files should be co-located
      with source files using the .test.ts or .spec.ts naming convention.


      Examples:

      - src/utils/parser.ts → src/utils/parser.test.ts

      - src/components/Button.tsx → src/components/Button.test.tsx
    fingerprint: testing-requirements
  - heading: Code review standards
    level: 2
    content: >
      TODO comments should be converted to GitHub issues before merging. They
      often get forgotten in the codebase.


      Instead of: // TODO: refactor this

      Do: Create issue, then // Issue #123: refactor this
    fingerprint: code-review-standards
  - heading: Public API documentation
    level: 2
    content: >
      Public API exports should include JSDoc comments explaining their purpose
      and usage. This helps with IDE intellisense and documentation generation.
    fingerprint: public-api-documentation
  - heading: Security practices
    level: 2
    content: >
      Never commit API keys, passwords, or tokens to version control. Use
      environment variables or secure secret management instead.


      Common patterns to avoid:

      - API_KEY = "sk_live_..."

      - password: "mypassword123"

      - token: "ghp_..."
    fingerprint: security-practices
  - heading: TypeScript type safety
    level: 2
    content: >
      Avoid using 'any' type as it defeats TypeScript's type safety. Use
      'unknown' for truly unknown types, or define proper interfaces.
    fingerprint: typescript-type-safety
