/**
 * Integration tests for Cursor exporter with section merging
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  mkdirSync,
  writeFileSync,
  rmSync,
  existsSync,
  readFileSync,
  mkdtempSync,
} from "fs";
import { join } from "path";
import { tmpdir } from "os";
import { CursorExporter } from "../../src/cursor/index.js";
import type { AlignSection } from "@aligntrue/schema";

describe("CursorExporter - Section Merging", () => {
  let testDir: string;
  let exporter: CursorExporter;

  beforeEach(() => {
    // Create temp directory for test with unique suffix to avoid collisions
    testDir = mkdtempSync(join(tmpdir(), "aligntrue-test-"));
    mkdirSync(join(testDir, ".cursor", "rules"), { recursive: true });

    exporter = new CursorExporter();
  });

  afterEach(() => {
    // Clean up temp directory
    if (existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true });
    }
  });

  it("should create new file when none exists", async () => {
    const sections: AlignSection[] = [
      {
        heading: "Testing",
        content: "Run tests before committing.",
        level: 2,
      },
    ];

    const result = await exporter.export(
      {
        scope: {
          path: ".",
          isDefault: true,
          normalizedPath: ".",
        },
        pack: { sections },
      },
      {
        outputDir: testDir,
        dryRun: false,
      },
    );

    expect(result.success).toBe(true);
    expect(result.filesWritten.length).toBe(1);

    const filePath = join(testDir, ".cursor", "rules", "aligntrue.mdc");
    expect(existsSync(filePath)).toBe(true);

    const content = readFileSync(filePath, "utf-8");
    expect(content).toContain("## Testing");
    expect(content).toContain("Run tests before committing.");
  });

  it("should preserve user-added sections", async () => {
    // Create existing file with user section
    const existingContent = `---
alwaysApply: true
---

## Testing

Run tests.

## My Personal Notes

These are my personal workflow notes.

---

**Generated by AlignTrue**
Content Hash: sha256:old123
`;

    const filePath = join(testDir, ".cursor", "rules", "aligntrue.mdc");
    writeFileSync(filePath, existingContent);

    // Sync with updated Testing section (but no Personal Notes in IR)
    const sections: AlignSection[] = [
      {
        heading: "Testing",
        content: "Run all tests before committing.",
        level: 2,
      },
    ];

    const result = await exporter.export(
      {
        scope: {
          path: ".",
          isDefault: true,
          normalizedPath: ".",
        },
        pack: { sections },
      },
      {
        outputDir: testDir,
        dryRun: false,
      },
    );

    expect(result.success).toBe(true);

    const content = readFileSync(filePath, "utf-8");

    // Should have updated Testing section
    expect(content).toContain("Run all tests before committing.");

    // Should preserve user's Personal Notes section
    expect(content).toContain("## My Personal Notes");
    expect(content).toContain("These are my personal workflow notes.");
  });

  it("should add team-managed markers", async () => {
    const sections: AlignSection[] = [
      {
        heading: "Security",
        content: "Validate all user input.",
        level: 2,
      },
    ];

    const result = await exporter.export(
      {
        scope: {
          path: ".",
          isDefault: true,
          normalizedPath: ".",
        },
        pack: { sections },
      },
      {
        outputDir: testDir,
        dryRun: false,
        managedSections: ["Security"],
      },
    );

    expect(result.success).toBe(true);

    const filePath = join(testDir, ".cursor", "rules", "aligntrue.mdc");
    const content = readFileSync(filePath, "utf-8");

    // Team-managed sections use HTML comment markers without emojis
    expect(content).toContain("## Security");
    expect(content).toContain("[TEAM-MANAGED]");
  });

  it("should report merge statistics in warnings", async () => {
    // Create existing file with user section
    const existingContent = `---
alwaysApply: true
---

## Testing

Run tests.

## My Notes

Personal notes.
`;

    const filePath = join(testDir, ".cursor", "rules", "aligntrue.mdc");
    writeFileSync(filePath, existingContent);

    const sections: AlignSection[] = [
      {
        heading: "Testing",
        content: "Run all tests.",
        level: 2,
      },
    ];

    const result = await exporter.export(
      {
        scope: {
          path: ".",
          isDefault: true,
          normalizedPath: ".",
        },
        pack: { sections },
      },
      {
        outputDir: testDir,
        dryRun: false,
      },
    );

    expect(result.success).toBe(true);

    // Verify that the file was created with merged content
    const filePath2 = join(testDir, ".cursor", "rules", "aligntrue.mdc");
    const content = readFileSync(filePath2, "utf-8");

    // File should contain the updated Testing section and preserved My Notes
    expect(content).toContain("## Testing");
    expect(content).toContain("Run all tests.");
    expect(content).toContain("## My Notes");
    expect(content).toContain("Personal notes.");
  });
});
