import type { AlignTrueConfig } from "@aligntrue/core";

/**
 * Cline exporter
 * Exports AlignTrue rules to Cline .clinerules format
 */

import { join } from "path";
import type {
  ScopedExportRequest,
  ExportOptions,
  ExportResult,
  ResolvedScope,
} from "../types.js";
import type { AlignSection } from "@aligntrue/schema";
import type { ModeHints } from "@aligntrue/core";
import { computeContentHash, getSections } from "@aligntrue/schema";
import { ExporterBase } from "../base/index.js";
import {
  extractModeConfig,
  applyRulePrioritization,
  generateSessionPreface,
  wrapRuleWithMarkers,
  shouldIncludeRule,
} from "../utils/index.js";

interface ExporterState {
  allRules: Array<{ rule: AlignRule; scopePath: string }>;
  allSections: Array<{ section: AlignSection; scopePath: string }>;
  useSections: boolean;
}

export class ClineExporter extends ExporterBase {
  name = "cline";
  version = "1.0.0";

  private state: ExporterState = {
    allRules: [],
    allSections: [],
    useSections: false,
  };

  async export(
    request: ScopedExportRequest,
    options: ExportOptions,
  ): Promise<ExportResult> {
    const { scope, rules, pack } = request;
    const { outputDir, dryRun = false, config } = options;

    const sections = getSections(pack);
    const useSections = sections.length > 0;

    if (
      this.state.allRules.length === 0 &&
      this.state.allSections.length === 0
    ) {
      this.state.useSections = useSections;
    }

    if ((!rules || rules.length === 0) && sections.length === 0) {
      return {
        success: true,
        filesWritten: [],
        contentHash: "",
      };
    }

    if (useSections) {
      sections.forEach((section) => {
        this.state.allSections.push({
          section,
          scopePath: this.formatScopePath(scope),
        });
      });
    } else {
      rules?.forEach((rule) => {
        this.state.allRules.push({
          rule,
          scopePath: this.formatScopePath(scope),
        });
      });
    }

    const outputPath = join(outputDir, ".clinerules");

    const { modeHints, maxBlocks, maxTokens } = extractModeConfig(
      this.name,
      config as AlignTrueConfig | undefined,
    );
    const { content, warnings } = this.generateClineRulesContent(
      modeHints,
      maxBlocks,
      maxTokens,
      options,
    );

    let contentHash: string;
    let fidelityNotes: string[];

    if (this.state.useSections) {
      const allSectionsIR = this.state.allSections.map(
        ({ section }) => section,
      );
      contentHash = computeContentHash({ sections: allSectionsIR });
      fidelityNotes = this.computeSectionFidelityNotes(allSectionsIR);
    } else {
      const allRulesIR = this.state.allRules.map(({ rule }) => rule);
      contentHash = computeContentHash({ rules: allRulesIR });
      fidelityNotes = this.computeFidelityNotes(allRulesIR);
    }

    const filesWritten = await this.writeFile(outputPath, content, dryRun);

    const result = this.buildResult(filesWritten, contentHash, fidelityNotes);

    if (warnings.length > 0) {
      result.warnings = warnings;
    }

    return result;
  }

  resetState(): void {
    this.state = {
      allRules: [],
      allSections: [],
      useSections: false,
    };
  }

  private formatScopePath(scope: ResolvedScope): string {
    if (scope.isDefault || scope.path === "." || scope.path === "") {
      return "all files";
    }
    return scope.path;
  }

  private generateClineRulesContent(
    modeHints: ModeHints,
    maxBlocks: number,
    maxTokens: number,
    options: ExportOptions,
  ): { content: string; warnings: string[] } {
    const lines: string[] = [];

    lines.push("# Cline Rules");
    lines.push("# Generated by AlignTrue");
    lines.push("");

    // Add session preface (as comments for plain text format)
    const prefaceLines = generateSessionPreface(modeHints);
    if (prefaceLines.length > 0) {
      prefaceLines.forEach((line) => lines.push(`# ${line}`));
      lines.push("");
    }

    // Apply prioritization
    const allRules = this.state.allRules.map(({ rule }) => rule);
    const { includedIds, warnings } = applyRulePrioritization(
      allRules,
      modeHints,
      maxBlocks,
      maxTokens,
    );

    // Generate rule sections
    this.state.allRules.forEach(({ rule, scopePath }) => {
      if (!shouldIncludeRule(rule.id, includedIds)) {
        return;
      }

      // Build rule content
      const ruleLines: string[] = [];
      ruleLines.push(`# Rule: ${rule.id}`);
      ruleLines.push(`# Severity: ${rule.severity.toUpperCase()}`);
      if (scopePath) {
        ruleLines.push(`# Scope: ${scopePath}`);
      }
      ruleLines.push("");
      if (rule.guidance) {
        rule.guidance
          .trim()
          .split("\n")
          .forEach((line) => {
            ruleLines.push(line);
          });
        ruleLines.push("");
      }
      ruleLines.push("---");

      // Wrap with markers
      const ruleContent = ruleLines.join("\n");
      lines.push(wrapRuleWithMarkers(rule, ruleContent, modeHints));
      lines.push("");
    });

    const allRulesIR = this.state.allRules.map(({ rule }) => rule);
    const contentHash = computeContentHash({ rules: allRulesIR });

    lines.push(`# Content Hash: ${contentHash}`);

    if (
      options.unresolvedPlugsCount !== undefined &&
      options.unresolvedPlugsCount > 0
    ) {
      lines.push(`# Unresolved Plugs: ${options.unresolvedPlugsCount}`);
    }

    return { content: lines.join("\n"), warnings };
  }

  /**
   * Compute fidelity notes for unmapped fields (custom for Cline)
   * Overrides base class to add Cline-specific messages
   */
  override computeFidelityNotes(rules: AlignRule[]): string[] {
    const notes: string[] = [];
    const unmappedFields = new Set<string>();

    rules.forEach((rule) => {
      if (rule.check) {
        unmappedFields.add("check");
      }
      if (rule.autofix) {
        unmappedFields.add("autofix");
      }
    });

    if (unmappedFields.has("check")) {
      notes.push(
        "Machine-checkable rules (check) not represented in .clinerules format",
      );
    }
    if (unmappedFields.has("autofix")) {
      notes.push("Autofix hints not represented in .clinerules format");
    }

    return notes;
  }
}

export default ClineExporter;
