/**
 * AGENTS.md starter template
 * Generated from canonical source to ensure consistency
 */

import { STARTER_RULES_CANONICAL } from "./starter-rules-canonical.js";

export function generateAgentsMdStarter(): string {
  let output = `# AGENTS.md

**Version:** v1
**Generated by:** AlignTrue

This file contains rules and guidance for AI coding agents.

`;

  // Generate rules from canonical source
  for (const rule of STARTER_RULES_CANONICAL) {
    // Convert severity to AGENTS.md format (uppercase)
    const severity = rule.severity.toUpperCase();

    // Convert applies_to array to comma-separated scope
    const scope = rule.applies_to.join(", ");

    output += `## Rule: ${rule.id}\n\n`;
    output += `**ID:** ${rule.id}\n`;
    output += `**Severity:** ${severity}\n`;
    output += `**Scope:** ${scope}\n\n`;
    output += `${rule.guidance}\n`;
    output += `---\n\n`;
  }

  output += `**Generated by AlignTrue**\n\n`;
  output += `💡 **Tip:** Edit these rules to match your project's needs, then run \`aligntrue sync\` to update other agents.\n`;

  return output;
}

/**
 * Get the default path for AGENTS.md starter template
 */
export function getAgentsMdStarterPath(): string {
  return "AGENTS.md";
}
