/**
 * Cursor starter template
 * Provides example rules in native .cursor/*.mdc format
 */

export function generateCursorStarter(): string {
  return `---
description: AlignTrue starter rules
alwaysApply: true
---
## Rule: quality.typescript.strict

**Severity:** error

**Applies to:**
- \`tsconfig.json\`

Enable strict mode in tsconfig.json.
This enforces noImplicitAny, strictNullChecks, and strictFunctionTypes.
Fix all TypeScript errors before committing.

## Rule: style.naming.conventions

**Severity:** error

**Applies to:**
- \`**/*.ts\`
- \`**/*.tsx\`

Follow these naming conventions:
- Classes: PascalCase (e.g., \`UserRepository\`)
- Functions/variables: camelCase (e.g., \`fetchUserData\`)
- Constants: UPPER_SNAKE_CASE (e.g., \`MAX_RETRIES\`)
- Private properties: prefix with underscore (e.g., \`_cache\`)

## Rule: quality.testing.required

**Severity:** warn

**Applies to:**
- \`src/**/*.ts\`
- \`src/**/*.tsx\`

Write unit tests for all new functions.
Test file naming: \`*.test.ts\` or \`*.spec.ts\`
Aim for >80% code coverage.

Examples:
- src/utils/parser.ts → src/utils/parser.test.ts
- src/components/Button.tsx → src/components/Button.test.tsx

## Rule: style.imports.organized

**Severity:** info

**Applies to:**
- \`**/*.ts\`
- \`**/*.tsx\`

Sort imports alphabetically.
Group imports: node modules first, then local modules.
Remove unused imports before committing.

Example:
\`\`\`typescript
// Node modules
import { readFile } from 'fs/promises'
import { join } from 'path'

// Local modules
import { parseConfig } from './config'
import { logger } from './logger'
\`\`\`

## Rule: quality.no.console-log

**Severity:** warn

**Applies to:**
- \`src/**/*.ts\`
- \`src/**/*.tsx\`

Don't use \`console.log()\` in production code.
Use a proper logging library instead.

For debugging during development, use:
- \`console.debug()\` for verbose logs
- \`console.info()\` for informational messages
- \`console.warn()\` for warnings
- \`console.error()\` for errors

---

**Generated by AlignTrue**

💡 **Tip:** Edit these rules to match your project's needs, then run \`aligntrue sync\` to update other agents.
`;
}

/**
 * Get the default path for Cursor starter template
 */
export function getCursorStarterPath(): string {
  return ".cursor/rules/aligntrue-starter.mdc";
}
