/**
 * Cursor starter template
 * Generated from canonical source to ensure consistency
 */

import { STARTER_RULES_CANONICAL } from "./starter-rules-canonical.js";

export function generateCursorStarter(): string {
  let output = `---
description: AlignTrue starter rules
alwaysApply: true
---\n`;

  // Generate rules from canonical source
  for (const rule of STARTER_RULES_CANONICAL) {
    output += `## Rule: ${rule.id}\n\n`;
    output += `**Severity:** ${rule.severity}\n\n`;
    output += `**Applies to:**\n`;
    rule.applies_to.forEach((pattern) => {
      output += `- \`${pattern}\`\n`;
    });
    output += `\n${rule.guidance}\n\n`;
  }

  output += `---\n\n`;
  output += `**Generated by AlignTrue**\n\n`;
  output += `💡 **Tip:** Edit these rules to match your project's needs, then run \`aligntrue sync\` to update other agents.\n`;

  return output;
}

/**
 * Get the default path for Cursor starter template
 */
export function getCursorStarterPath(): string {
  return ".cursor/rules/aligntrue-starter.mdc";
}
