id: overlay-demo-align
version: "1.0.0"
spec_version: "1"

profile:
  id: example/overlay-demo
  version: "1.0.0"
  name: Overlays Demo Align
  summary: Demonstrate fork-safe customization using overlays

sections:
  - heading: "Avoid console.log in production code"
    level: 2
    content: |
      Use proper logging library instead of console.log.
      Console statements can leak sensitive information and
      clutter production logs.

      Good: logger.info("User logged in")
      Bad: console.log("User logged in")
    fingerprint: "no-console-log"

  - heading: "Limit cyclomatic complexity"
    level: 2
    content: |
      Keep functions simple with cyclomatic complexity under threshold.
      Complex functions are hard to test and maintain.

      Refactor complex functions into smaller, focused functions.
    fingerprint: "max-complexity"
    check:
      inputs:
        threshold: 10
        excludeComments: false

  - heading: "Use const for variables that are never reassigned"
    level: 2
    content: |
      Use const instead of let for variables that are never reassigned.
      This makes code more predictable and prevents accidental reassignment.

      Good: const user = getUser();
      Bad: let user = getUser();
    fingerprint: "prefer-const"
    autofix:
      enabled: true
      description: "Replace let with const"
