/**
 * Aider config exporter
 * Exports AlignTrue rules to .aider.conf.yml configuration format
 */

import { join } from "path";
import type {
  ScopedExportRequest,
  ExportOptions,
  ExportResult,
} from "../types.js";
import { computeContentHash } from "@aligntrue/schema";
import { ExporterBase } from "../base/index.js";

export class AiderConfigExporter extends ExporterBase {
  name = "aider-config";
  version = "1.0.0";

  async export(
    request: ScopedExportRequest,
    options: ExportOptions,
  ): Promise<ExportResult> {
    const { pack } = request;
    const { outputDir, dryRun = false } = options;

    const sections = pack.sections;

    if (sections.length === 0) {
      return {
        success: true,
        filesWritten: [],
        contentHash: "",
      };
    }

    const outputPath = join(outputDir, ".aider.conf.yml");
    const contentHash = computeContentHash({ sections });
    const fidelityNotes = this.computeSectionFidelityNotes(sections);

    // Generate YAML format
    const lines: string[] = [];
    lines.push("# Generated by AlignTrue");
    lines.push("# Aider configuration");
    lines.push("");
    lines.push("version: v1");
    lines.push(`content_hash: ${contentHash}`);
    lines.push("");
    lines.push("# Rules:");
    sections.forEach((section) => {
      lines.push(`  - ${section.heading}`);
    });

    const content = lines.join("\n") + "\n";
    const filesWritten = await this.writeFile(
      outputPath,
      content,
      dryRun,
      options,
    );

    return this.buildResult(filesWritten, contentHash, fidelityNotes);
  }

  resetState(): void {
    // Stateless exporter
  }
}

export default AiderConfigExporter;
