/**
 * Tests for section parser utility
 */

import { describe, it, expect } from "vitest";
import {
  parseAgentsMd,
  parseCursorMdc,
  parseGenericMarkdown,
} from "../../src/utils/section-parser.js";

describe("parseAgentsMd", () => {
  it("should parse a simple AGENTS.md file", () => {
    const content = `# AGENTS.md

**Version:** v1
**Generated by:** AlignTrue

This file contains rules and guidance for AI coding agents.

## Testing

Run tests before committing.

## Documentation

Keep docs up to date.

---

**Generated by AlignTrue**
Content Hash: sha256:abc123
`;

    const result = parseAgentsMd(content);

    expect(result.sections).toHaveLength(2);
    expect(result.sections[0]?.heading).toBe("Testing");
    expect(result.sections[0]?.content).toContain(
      "Run tests before committing",
    );
    expect(result.sections[0]?.level).toBe(2);
    expect(result.sections[1]?.heading).toBe("Documentation");
    expect(result.contentHash).toBe("sha256:abc123");
  });

  it("should detect team-managed markers", () => {
    const content = `# AGENTS.md

<!-- [TEAM-MANAGED]: This section is managed by your team.
Local edits will be preserved in backups but may be overwritten on next sync.
To keep changes, rename the section or remove from managed list. -->

## Security

Always validate input.
`;

    const result = parseAgentsMd(content);

    expect(result.sections).toHaveLength(1);
    expect(result.sections[0]?.heading).toBe("Security");
    expect(result.sections[0]?.isTeamManaged).toBe(true);
  });

  it("should handle nested headings", () => {
    const content = `# Main

## Level 2

Content here.

### Level 3

More content.
`;

    const result = parseAgentsMd(content);

    expect(result.sections).toHaveLength(3);
    expect(result.sections[0]?.level).toBe(1);
    expect(result.sections[1]?.level).toBe(2);
    expect(result.sections[2]?.level).toBe(3);
  });

  it("should compute section hashes", () => {
    const content = `## Testing

Run tests before committing.
`;

    const result = parseAgentsMd(content);

    expect(result.sections[0]?.hash).toBeDefined();
    expect(result.sections[0]?.hash).toMatch(/^[a-f0-9]{64}$/);
  });
});

describe("parseCursorMdc", () => {
  it("should parse Cursor .mdc with YAML frontmatter", () => {
    const content = `---
alwaysApply: true
---

## Testing

Run tests before committing.

---

**Generated by AlignTrue**
Content Hash: sha256:def456
`;

    const result = parseCursorMdc(content);

    expect(result.sections).toHaveLength(1);
    expect(result.sections[0]?.heading).toBe("Testing");
    expect(result.header).toContain("alwaysApply: true");
    expect(result.contentHash).toBe("sha256:def456");
  });

  it("should handle multiple sections with frontmatter", () => {
    const content = `---
intelligent: true
description: Development rules
---

## Testing

Run tests.

## Documentation

Write docs.
`;

    const result = parseCursorMdc(content);

    expect(result.sections).toHaveLength(2);
    expect(result.header).toContain("intelligent: true");
  });
});

describe("parseGenericMarkdown", () => {
  it("should parse generic markdown files", () => {
    const content = `# CLAUDE.md

## Testing

Run tests.

## Debugging

Use debugger.
`;

    const result = parseGenericMarkdown(content);

    // File title "# CLAUDE.md" is skipped as file title, only ## sections counted
    expect(result.sections).toHaveLength(2);
    expect(result.sections[0]?.heading).toBe("Testing");
    expect(result.sections[1]?.heading).toBe("Debugging");
  });

  it("should handle empty files", () => {
    const result = parseGenericMarkdown("");

    expect(result.sections).toHaveLength(0);
    expect(result.header).toBe("");
    expect(result.footer).toBe("");
  });
});

describe("File title detection", () => {
  it("should skip file title heading in AGENTS.md", () => {
    const content = `# AGENTS.md

**Version:** v1

## Testing

Run tests.

## Security

Validate input.
`;

    const result = parseAgentsMd(content);

    // Should skip "# AGENTS.md" and only parse ## sections
    expect(result.sections).toHaveLength(2);
    expect(result.sections[0]?.heading).toBe("Testing");
    expect(result.sections[1]?.heading).toBe("Security");
  });

  it("should handle AGENTS.md with no file title", () => {
    const content = `## Testing

Run tests.

## Security

Validate input.
`;

    const result = parseAgentsMd(content);

    expect(result.sections).toHaveLength(2);
    expect(result.sections[0]?.heading).toBe("Testing");
  });
});

describe("Content hash extraction", () => {
  it("should extract hash from standard footer", () => {
    const content = `## Testing

Run tests.

---

**Generated by AlignTrue**
Content Hash: sha256:5fd1a17f08f15c95cc49dfb06866c4a98f92f5207176a0a0f3f64d8adf59d4ab
`;

    const result = parseAgentsMd(content);

    expect(result.contentHash).toBe(
      "sha256:5fd1a17f08f15c95cc49dfb06866c4a98f92f5207176a0a0f3f64d8adf59d4ab",
    );
  });

  it("should handle footer with extra text", () => {
    const content = `## Testing

Run tests.

---

**Generated by AlignTrue**
Last updated: 2025-01-01
Content Hash: sha256:abc123def456abc123def456abc123def456abc123def456abc123def456abc1
Fidelity: 100%
`;

    const result = parseAgentsMd(content);

    expect(result.contentHash).toBe(
      "sha256:abc123def456abc123def456abc123def456abc123def456abc123def456abc1",
    );
  });

  it("should return undefined when no hash present", () => {
    const content = `## Testing

Run tests.
`;

    const result = parseAgentsMd(content);

    expect(result.contentHash).toBeUndefined();
  });
});

describe("Team-managed markers", () => {
  it("should detect HTML comment markers", () => {
    const content = `<!-- [TEAM-MANAGED]: This section is managed by your team. -->

## Security

Validate input.
`;

    const result = parseAgentsMd(content);

    expect(result.sections[0]?.isTeamManaged).toBe(true);
  });

  it("should preserve section heading without markers", () => {
    const content = `## Security

Validate input.
`;

    const result = parseAgentsMd(content);

    expect(result.sections[0]?.heading).toBe("Security");
    expect(result.sections[0]?.isTeamManaged).toBeFalsy();
  });

  it("should handle mixed managed and non-managed sections", () => {
    const content = `## Testing

Run tests.

<!-- [TEAM-MANAGED]: This section is managed by your team. -->

## Security

Validate input.

## Documentation

Write docs.
`;

    const result = parseAgentsMd(content);

    expect(result.sections).toHaveLength(3);
    expect(result.sections[0]?.isTeamManaged).toBeFalsy();
    expect(result.sections[1]?.isTeamManaged).toBe(true);
    expect(result.sections[2]?.isTeamManaged).toBeFalsy();
  });
});
