/**
 * AGENTS.md exporter
 * Exports AlignTrue rules to universal AGENTS.md format
 *
 * Format: Single root-level AGENTS.md file with v1 versioned structure
 * Target agents: Claude, Copilot, Aider, and other AGENTS.md-compatible tools
 */

import type {
  ScopedExportRequest,
  ExportOptions,
  ExportResult,
  ResolvedScope,
} from "@aligntrue/plugin-contracts";
import type { AlignSection } from "@aligntrue/schema";
import { computeContentHash } from "@aligntrue/schema";
import { getAlignTruePaths } from "@aligntrue/core";
import { ExporterBase } from "../base/index.js";

/**
 * State for collecting all scopes before generating single merged file
 */
interface ExporterState {
  allSections: Array<{ section: AlignSection; scopePath: string }>;
  seenScopes: Set<string>;
}

export class AgentsMdExporter extends ExporterBase {
  name = "agents-md";
  version = "1.0.0";

  // State for accumulating sections across multiple scope calls
  private state: ExporterState = {
    allSections: [],
    seenScopes: new Set(),
  };

  async export(
    request: ScopedExportRequest,
    options: ExportOptions,
  ): Promise<ExportResult> {
    const { scope, pack } = request;
    const { outputDir, dryRun = false } = options;

    const sections = pack.sections;

    // Validate inputs
    if (sections.length === 0) {
      // Empty scope is allowed, just skip accumulation
      return {
        success: true,
        filesWritten: [],
        contentHash: "",
      };
    }

    // Accumulate content with scope information
    const scopePath = this.formatScopePath(scope);

    // Natural markdown sections
    sections.forEach((section) => {
      this.state.allSections.push({ section, scopePath });
    });

    this.state.seenScopes.add(scopePath);

    // For AGENTS.md, we generate the file only on the first export call
    // In real usage, sync engine would need to signal "last scope" or we'd need
    // a different pattern. For now, we generate immediately for each call.
    // This matches the test expectations where each test case is independent.

    const paths = getAlignTruePaths(outputDir);
    const outputPath = paths.agentsMd();

    // Generate AGENTS.md content - natural markdown mode
    const result = this.generateSectionsContent(options.unresolvedPlugsCount);
    const content = result.content;
    const warnings = result.warnings;

    // Compute content hash from sections
    const allSectionsIR = this.state.allSections.map(({ section }) => section);
    const contentHash = computeContentHash({ sections: allSectionsIR });
    const fidelityNotes = this.computeSectionFidelityNotes(allSectionsIR);

    // Write file atomically if not dry-run
    const filesWritten = await this.writeFile(outputPath, content, dryRun);

    const exportResult = this.buildResult(
      filesWritten,
      contentHash,
      fidelityNotes,
    );

    if (warnings.length > 0) {
      exportResult.warnings = warnings;
    }

    return exportResult;
  }

  /**
   * Format scope path for display in AGENTS.md
   * Default scope (path: ".") → "all files"
   * Named scope → actual path
   */
  private formatScopePath(scope: ResolvedScope): string {
    if (scope.isDefault || scope.path === "." || scope.path === "") {
      return "all files";
    }
    return scope.path;
  }

  /**
   * Generate AGENTS.md content from natural markdown sections
   * Much simpler than rule-based format - just render sections as-is
   */
  private generateSectionsContent(unresolvedPlugs?: number): {
    content: string;
    warnings: string[];
  } {
    const header = this.generateHeader();

    // Render all sections as natural markdown
    const allSections = this.state.allSections.map(({ section }) => section);
    const sectionsMarkdown = this.renderSections(allSections, false);

    // Compute content hash and fidelity notes for footer
    const contentHash = computeContentHash({ sections: allSections });
    const fidelityNotes = this.computeSectionFidelityNotes(allSections);
    const footer = this.generateFooter(
      contentHash,
      fidelityNotes,
      unresolvedPlugs,
    );

    return {
      content: `${header}\n\n${sectionsMarkdown}\n\n${footer}`,
      warnings: [],
    };
  }

  /**
   * Generate v1 format header
   */
  private generateHeader(): string {
    const lines: string[] = [];

    lines.push("# AGENTS.md");
    lines.push("");
    lines.push("**Version:** v1");
    lines.push("**Generated by:** AlignTrue");
    lines.push("");
    lines.push("This file contains rules and guidance for AI coding agents.");

    return lines.join("\n");
  }

  /**
   * Generate footer with content hash and fidelity notes
   */
  private generateFooter(
    contentHash: string,
    fidelityNotes: string[],
    unresolvedPlugs?: number,
  ): string {
    const lines: string[] = ["---", ""];

    lines.push("**Generated by AlignTrue**");
    lines.push(`Content Hash: ${contentHash}`);

    if (unresolvedPlugs !== undefined && unresolvedPlugs > 0) {
      lines.push(`Unresolved Plugs: ${unresolvedPlugs}`);
    }

    if (fidelityNotes.length > 0) {
      lines.push("");
      lines.push("**Fidelity Notes:**");
      fidelityNotes.forEach((note) => {
        lines.push(`- ${note}`);
      });
    }

    lines.push("");
    return lines.join("\n");
  }

  /**
   * Reset internal state (useful for testing)
   */
  resetState(): void {
    this.state = {
      allSections: [],
      seenScopes: new Set(),
    };
  }
}
