/**
 * WARP.md exporter
 * Exports AlignTrue rules to Warp-specific WARP.md format
 */

import { join } from 'path'
import type { ExporterPlugin, ScopedExportRequest, ExportOptions, ExportResult, ResolvedScope } from '../types.js'
import type { AlignRule } from '@aligntrue/schema'
import { canonicalizeJson, computeHash } from '@aligntrue/schema'
import { AtomicFileWriter } from '@aligntrue/file-utils'

interface ExporterState {
  allRules: Array<{ rule: AlignRule; scopePath: string }>
  seenScopes: Set<string>
}

export class WarpMdExporter implements ExporterPlugin {
  name = 'warp-md'
  version = '1.0.0'
  
  private state: ExporterState = {
    allRules: [],
    seenScopes: new Set(),
  }

  async export(request: ScopedExportRequest, options: ExportOptions): Promise<ExportResult> {
    const { scope, rules } = request
    const { outputDir, dryRun = false } = options

    if (!rules || rules.length === 0) {
      return {
        success: true,
        filesWritten: [],
        contentHash: '',
      }
    }

    const scopePath = this.formatScopePath(scope)
    rules.forEach(rule => {
      this.state.allRules.push({ rule, scopePath })
    })
    this.state.seenScopes.add(scopePath)

    const outputPath = join(outputDir, 'WARP.md')
    const content = this.generateWarpMdContent()
    
    const allRulesIR = this.state.allRules.map(({ rule }) => rule)
    const irContent = JSON.stringify({ rules: allRulesIR })
    const contentHash = computeHash(canonicalizeJson(irContent))
    
    const fidelityNotes = this.computeFidelityNotes(allRulesIR)
    
    if (!dryRun) {
      const writer = new AtomicFileWriter()
      writer.write(outputPath, content)
    }

    const result: ExportResult = {
      success: true,
      filesWritten: dryRun ? [] : [outputPath],
      contentHash,
    }

    if (fidelityNotes.length > 0) {
      result.fidelityNotes = fidelityNotes
    }

    return result
  }

  resetState(): void {
    this.state = {
      allRules: [],
      seenScopes: new Set(),
    }
  }

  private formatScopePath(scope: ResolvedScope): string {
    if (scope.isDefault || scope.path === '.' || scope.path === '') {
      return 'all files'
    }
    return scope.path
  }

  private generateWarpMdContent(): string {
    const lines: string[] = []
    
    lines.push('# WARP.md')
    lines.push('')
    lines.push('**Version:** v1')
    lines.push('**Generated by:** AlignTrue')
    lines.push('')
    lines.push('This file contains rules and guidance for Warp.')
    lines.push('')

    this.state.allRules.forEach(({ rule, scopePath }) => {
      lines.push(`## Rule: ${rule.id}`)
      lines.push('')
      lines.push(`**ID:** ${rule.id}`)
      lines.push(`**Severity:** ${this.mapSeverity(rule.severity)}`)
      if (scopePath) {
        lines.push(`**Scope:** ${scopePath}`)
      }
      lines.push('')
      if (rule.guidance) {
        lines.push(rule.guidance.trim())
        lines.push('')
      }
      lines.push('---')
      lines.push('')
    })

    const allRulesIR = this.state.allRules.map(({ rule }) => rule)
    const irContent = JSON.stringify({ rules: allRulesIR })
    const contentHash = computeHash(canonicalizeJson(irContent))
    const fidelityNotes = this.computeFidelityNotes(allRulesIR)

    lines.push('**Generated by AlignTrue**')
    lines.push(`Content Hash: ${contentHash}`)
    
    if (fidelityNotes.length > 0) {
      lines.push('')
      lines.push('**Fidelity Notes:**')
      fidelityNotes.forEach(note => {
        lines.push(`- ${note}`)
      })
    }

    return lines.join('\n')
  }

  private mapSeverity(severity: 'error' | 'warn' | 'info'): string {
    const map: Record<string, string> = {
      error: 'ERROR',
      warn: 'WARN',
      info: 'INFO',
    }
    return map[severity] || 'WARN'
  }

  private computeFidelityNotes(rules: AlignRule[]): string[] {
    const notes: string[] = []
    const unmappedFields = new Set<string>()
    const vendorFields = new Set<string>()

    rules.forEach(rule => {
      if (rule.check) {
        unmappedFields.add('check')
      }
      if (rule.autofix) {
        unmappedFields.add('autofix')
      }
      if (rule.vendor) {
        Object.keys(rule.vendor).forEach(agent => {
          if (agent !== '_meta') {
            vendorFields.add(agent)
          }
        })
      }
    })

    if (unmappedFields.has('check')) {
      notes.push('Machine-checkable rules (check) not represented in WARP.md format')
    }
    if (unmappedFields.has('autofix')) {
      notes.push('Autofix hints not represented in WARP.md format')
    }
    if (vendorFields.size > 0) {
      const agents = Array.from(vendorFields).sort().join(', ')
      notes.push(`Vendor metadata for agents preserved but not extracted: ${agents}`)
    }

    return notes
  }
}

export default WarpMdExporter

